# Generated by Django 2.2.12 on 2022-04-16 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='Enter Item', max_length=50)),
                ('type', models.CharField(choices=[('F', 'Fresh Produce'), ('P', 'pantry')], default='F', max_length=50)),
                ('exp', models.DateField(default=1988, verbose_name='exp date')),
                ('desc', models.TextField(default='Enter Description', max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
