# Generated by Django 2.2.12 on 2022-04-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fresh',
        ),
        migrations.DeleteModel(
            name='Pantry',
        ),
    ]
