# Generated by Django 2.2.12 on 2022-04-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grub',
            name='exp',
            field=models.IntegerField(default=2022, verbose_name='exp date'),
        ),
    ]
