# Generated by Django 4.0.3 on 2022-04-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220417_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='grub',
            name='url',
            field=models.CharField(default='Choose Photo', max_length=200),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
