# Generated by Django 4.0.3 on 2022-04-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_grub_url_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grub',
            name='url',
            field=models.FileField(default='Choose Photo', max_length=200, upload_to=''),
        ),
    ]
