# Generated by Django 4.0.3 on 2022-04-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_grub_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grub',
            name='url',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
