# Generated by Django 4.0.3 on 2022-04-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_grub_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grub',
            name='item',
            field=models.CharField(default='', max_length=50),
        ),
    ]
