# Generated by Django 4.0.3 on 2022-04-19 23:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_grub_desc_alter_grub_exp_alter_grub_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grub',
            name='url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, max_length=200, null=True, upload_to=''), size=5),
        ),
    ]
