# Generated by Django 2.2.12 on 2022-04-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20220420_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grub',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
