# Generated by Django 2.2.12 on 2022-04-20 03:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20220420_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grub',
            name='url',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=5),
        ),
    ]
