# Generated by Django 2.2.12 on 2022-04-20 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20220420_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grub',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='grub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Grub'),
        ),
    ]
