# Generated by Django 4.0.3 on 2022-04-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grub',
            name='price',
        ),
        migrations.AlterField(
            model_name='grub',
            name='option',
            field=models.CharField(choices=[('Pick-up', 'Pick-Up'), ('Delivery', 'Delivery')], default='Pick-up', max_length=10),
        ),
    ]
