# Generated by Django 2.2.12 on 2022-04-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_grub_price_alter_grub_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grub',
            name='exp',
            field=models.TextField(blank=True, null=True, verbose_name='exp date'),
        ),
    ]
